[package]
name = "core-ops"
version = "2.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
libc = "0.2.153"
log = { version = "0.4", features = ["kv"] }
miette = { version = "7.2.0", features = ["fancy"] }
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.8", default-features = false, features = ["parse"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
systemd-journal-logger = "2.2.2"
tempfile = "3.10.1"
thiserror = "1.0.58"
time = { version = "0.3.36", features = ["formatting"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "core-ops"
path = "src/main.rs"

[[bin]]
name = "core-ops-verify"
path = "src/bin/core-ops-verify.rs"

[[bin]]
name = "core-ops-release"
path = "src/bin/core-ops-release.rs"
